### ISSUE TITLE
❓ Question - Material3 button does not work without root

### ISSUE THREAD

**Issue by ZM71** [Rikj000/Android-Auto-XLauncher-Unlocked#11]
Material3 button does nothing.

Edit by @Rikj000: User does not have root.

**Comment by Rikj000** [comment]
PEBKAC (Problem Exists Between Keyboard And Chair)... :unamused: 

If you could read the [ReadMe](https://github.com/Rikj000/Android-Auto-XLauncher-Unlocked#features),   
then you'd know that you need root for that feature,   
in issue #10 you stated that you do not have root,   
so of course it does not work for you.

**Comment by ZM71** [comment]
Bruh why does every app likr like this require stupid root doesn't any app have non-root?

**Comment by Rikj000** [comment]
@ZM71 feel free to implement #5 yourself if you require those features on a non-rooted device,   
and send a Pull Request of your work, then I'll review it and will merge it if it's decent.

Also it's very rude of you to complain about lack of features,   
when you're using free software, for which I'm not paid a cent,   
which I've written in my free time, I do not work for you.

Ungratefulness from users like you take the fun out of FOSS development,   
please refrain from doing so in the future.

**Comment by ZM71** [comment]
Rooting a device for Android Auto is so unnecessary this app is still useful tho.
