### ISSUE TITLE
❓ Help Wanted - Not working anymore 

### ISSUE THREAD

**Issue by daniu-de** [Rikj000/Android-Auto-XLauncher-Unlocked#4]
I installed everything as described and I could see osmand on the car screen but not even a week later (and unfortunately quite some app and systems: lineage, google maps, osmand) I cannot see osmand anymore ...

**Comment by Rikj000** [comment]
For me all still works as expected.

Please verify if LSPosed is still configured correctly, as shown here:
https://xdaforums.com/t/release-v2-0-1-android-auto-xlauncher-unlocked-aaxlu.4572697/post-89077999
Make sure to reboot after configuring LSPosed.

If AAXLU on it's own is not enough to make 3th party apps show up in AA, then checkout my post here:
https://xdaforums.com/t/screen2auto-new-app-for-aa-smartphone-mirroring-only-for-root-devices.4062787/post-88392893

**Comment by daniu-de** [comment]
No idea wjy but somehow it works again

(However now the car got a.problem ... with the engine)

I know now: the AA update disabled developer settings ...

**Comment by Rikj000** [comment]
Good to hear the app works for you.   
Hope you'll get your car fixed soon!

**Comment by daniu-de** [comment]
I found out that AA disables the developer mode upon update ...
